### ISSUE TITLE
PDF 번역이 실패합니다

### ISSUE THREAD

**Issue by Zeta611** [Zeta611/easyword-translator#3]
@retato-snu PDF 몇 개에 대해서 시도해보니 번역이 실패합니다.

```python
Traceback (most recent call last):
  File "/Users/jay/Library/Caches/pypoetry/virtualenvs/easyword-translator-Wofia9Ex-py3.12/lib/python3.12/site-packages/gradio/queueing.py", line 528, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jay/Library/Caches/pypoetry/virtualenvs/easyword-translator-Wofia9Ex-py3.12/lib/python3.12/site-packages/gradio/route_utils.py", line 270, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jay/Library/Caches/pypoetry/virtualenvs/easyword-translator-Wofia9Ex-py3.12/lib/python3.12/site-packages/gradio/blocks.py", line 1908, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jay/Library/Caches/pypoetry/virtualenvs/easyword-translator-Wofia9Ex-py3.12/lib/python3.12/site-packages/gradio/blocks.py", line 1485, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jay/Library/Caches/pypoetry/virtualenvs/easyword-translator-Wofia9Ex-py3.12/lib/python3.12/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jay/Library/Caches/pypoetry/virtualenvs/easyword-translator-Wofia9Ex-py3.12/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/Users/jay/Library/Caches/pypoetry/virtualenvs/easyword-translator-Wofia9Ex-py3.12/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jay/Library/Caches/pypoetry/virtualenvs/easyword-translator-Wofia9Ex-py3.12/lib/python3.12/site-packages/gradio/utils.py", line 808, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "/Users/jay/Developer/easyword-translator/easyword_translator/run.py", line 206, in transalte_pdf
    translation += translate(".".join(sentences[i : i + 50])) + ". "
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jay/Developer/easyword-translator/easyword_translator/run.py", line 92, in translate
    initial_translation = chainer(messages).invoke({})
                          ^^^^^^^^^^^^^^^^^
  File "/Users/jay/Developer/easyword-translator/easyword_translator/run.py", line 61, in chainer
    return ChatPromptTemplate.from_messages(messages) | llm | StrOutputParser()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jay/Library/Caches/pypoetry/virtualenvs/easyword-translator-Wofia9Ex-py3.12/lib/python3.12/site-packages/langchain_core/prompts/chat.py", line 970, in from_messages
    _convert_to_message(message, template_format) for message in messages
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jay/Library/Caches/pypoetry/virtualenvs/easyword-translator-Wofia9Ex-py3.12/lib/python3.12/site-packages/langchain_core/prompts/chat.py", line 1226, in _convert_to_message
    _message = _create_template_from_message_type(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jay/Library/Caches/pypoetry/virtualenvs/easyword-translator-Wofia9Ex-py3.12/lib/python3.12/site-packages/langchain_core/prompts/chat.py", line 1142, in _create_template_from_message_type
    message: BaseMessagePromptTemplate = HumanMessagePromptTemplate.from_template(
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jay/Library/Caches/pypoetry/virtualenvs/easyword-translator-Wofia9Ex-py3.12/lib/python3.12/site-packages/langchain_core/prompts/chat.py", line 423, in from_template
    prompt: Union[StringPromptTemplate, List] = PromptTemplate.from_template(
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jay/Library/Caches/pypoetry/virtualenvs/easyword-translator-Wofia9Ex-py3.12/lib/python3.12/site-packages/langchain_core/prompts/prompt.py", line 244, in from_template
    input_variables = get_template_variables(template, template_format)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jay/Library/Caches/pypoetry/virtualenvs/easyword-translator-Wofia9Ex-py3.12/lib/python3.12/site-packages/langchain_core/prompts/string.py", line 209, in get_template_variables
    input_variables = {
                      ^
ValueError: unexpected '{' in field name
```

**Comment by retato-snu** [comment]
{, } 를 포함하는 글을 번역하지 못합니다. f-string을 사용해서 생긴 것으로 생각됩니다.

**Comment by Zeta611** [comment]
```python
def chainer(messages):
    return ChatPromptTemplate.from_messages(messages) | llm | StrOutputParser()
```
를 그냥
```python
llm = llm | StrOutputParser()
```
로 바꾸고, 기존의 `chainer(messages).invoke({})`들을 그냥 `llm.invoke(messages)`로 하면 잘 될까요?
